export const BimWidgetCubeMap: { [key: string]: string } = {
	'2673': 'Top',
	'4015': 'Bottom',
	'0231': 'Front',
	'5764': 'Back',
	'1375': 'Right',
	'4620': 'Left',
	'3': 'RoofSouthEast',
	'2': 'RoofSouthWest',
	'7': 'RoofNorthEast',
	'6': 'RoofNorthWest',
	'1': 'BottomSouthEast',
	'0': 'BottomSouthWest',
	'4': 'BottomNorthWest',
	'5': 'BottomNorthEast',
	'32': 'RoofFront',
	'76': 'RoofBack',
	'37': 'RoofRight',
	'26': 'RoofLeft',
	'01': 'BottomFront',
	'45': 'BottomBack',
	'15': 'BottomRight',
	'04': 'BottomLeft',
	'13': 'SouthEast',
	'20': 'SouthWest',
	'57': 'NorthEast',
	'64': 'NorthWest'
}
